### ISSUE TITLE
Feature request: delete item from quickfix / location list.

### ISSUE THREAD

**Issue by ghillb** [stevearc/qf_helper.nvim#2]
Hi, one feature I'm missing with this plugin, that [vim-qf offers](https://github.com/romainl/vim-qf/issues/117#issuecomment-808878354), is:

Remove single lines or multiple lines from the list via `:Reject`. For example a single line can be removed via:
```lua
 vim.api.nvim_buf_set_keymap(0, '', 'dd', ':.Reject<cr>', { noremap = true, silent = true })
```
Is that something that you would consider for this plugin?

**Comment by stevearc** [comment]
Yeah I think that's a reasonable idea. I've implemented `:Keep` and `:Reject` similarly to vim-qf (no pattern filtering, since if you need that I think `:Cfilter` serves that purpose). I also didn't add any keymap by default since it could potentially conflict with the behavior of other plugins (e.g. quickfix-reflector).
