### ISSUE TITLE
Is this plugin being developed anymore?

### ISSUE THREAD

**Issue by krishnakumarg1984** [stevearc/qf_helper.nvim#8]
I see that the last commit was a few months ago. Furthermore, I saw that you had asked the plugin to be removed from the awesome-neovim list.

If this plugin is deprecated, what plugin would you recommend for quickfix list niceties?

**Comment by stevearc** [comment]
I removed it from awesome-neovim because I have some issues with it and in general don't think the quality is at the level where I'm happy to advertise it. The functionality still works, and I'll still fix bug reports and merge PRs, but if I get the time to do more work on this it will likely be to do a large refactor with breaking changes.

Not sure which features you need, but I know a lot of people use [nvim-bqf](https://github.com/kevinhwang91/nvim-bqf) and though I haven't used it myself, it seems like a high quality project.

**Comment by mxgrn** [comment]
Oh, [nvim-bqf](https://github.com/kevinhwang91/nvim-bqf) is truly awesome, thanks for the pointer!

**Comment by astier** [comment]
I personally use both qf_helper and bqf together because they serve me different purposes.

**Comment by stevearc** [comment]
This plugin is officially no longer being developed. I have moved all of my quickfix efforts to https://github.com/stevearc/quicker.nvim
